// Package workerws implements the official WebSocket adapter for the public
// HumanAgent WorkerTransport port. The wire protocol is intentionally small:
// domain identities and settlement receipts remain defined by package agent.
package workerws

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
)

const (
	// ProtocolVersion is bumped for incompatible wire changes. It is unrelated
	// to agent.WorkerTransportContractMajor, which versions the Go port.
	ProtocolVersion = "1"
	// SessionHeader is generated by a remote worker for each WebSocket dial. It
	// is never accepted as a durable task, command, or delivery identity.
	SessionHeader = "X-Human-Agent-Worker-Session"
)

type messageType string

const (
	messageHello         messageType = "hello"
	messageAssignment    messageType = "assignment"
	messageAssignmentACK messageType = "assignment_ack"
	messageEvent         messageType = "event"
	messageEventReceipt  messageType = "event_receipt"
)

type envelope struct {
	Version string          `json:"version"`
	Type    messageType     `json:"type"`
	Payload json.RawMessage `json:"payload,omitempty"`
}

func newEnvelope(kind messageType, payload any) (envelope, error) {
	var raw json.RawMessage
	if payload != nil {
		encoded, err := json.Marshal(payload)
		if err != nil {
			return envelope{}, err
		}
		raw = encoded
	}
	return envelope{Version: ProtocolVersion, Type: kind, Payload: raw}, nil
}

func (message envelope) validateInbound(allowed ...messageType) error {
	if message.Version != ProtocolVersion {
		return fmt.Errorf("unsupported Agent worker protocol version %q", message.Version)
	}
	for _, kind := range allowed {
		if message.Type == kind {
			return nil
		}
	}
	return fmt.Errorf("unexpected Agent worker message type %q", message.Type)
}

func decodePayload[T any](message envelope) (T, error) {
	var value T
	if len(message.Payload) == 0 {
		return value, errors.New("Agent worker message payload is required")
	}
	if err := decodeStrictJSON(message.Payload, &value); err != nil {
		return value, fmt.Errorf("decode Agent worker %s payload: %w", message.Type, err)
	}
	return value, nil
}

func decodeStrictJSON(encoded []byte, target any) error {
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return err
	}
	if err := decoder.Decode(new(any)); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("multiple JSON values are not allowed")
		}
		return err
	}
	return nil
}

type hello struct {
	Authority string `json:"authority"`
	Worker    string `json:"worker"`
	Session   string `json:"session"`
}
