// Package workerproto defines the private, versioned gateway-to-TUI protocol.
package workerproto

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/vibe-agi/human/internal/completion"
)

const Version = "1"

const (
	// GatewayEventOwner is reserved for durable receipts of synthetic terminal
	// events generated by the gateway. workerws refuses authenticated worker
	// principals with this subject so it can never collide with a real owner.
	GatewayEventOwner = "human-gateway"
	// WorkerInstanceHeader distinguishes one running Human worker from another
	// process using the same authenticated subject. It remains stable across
	// every reconnect made by one Client instance.
	WorkerInstanceHeader = "X-Human-Worker-Instance"
	// WorkerInstanceConflictReason is machine-stable so clients can stop a
	// futile reconnect loop while still showing an actionable diagnosis.
	WorkerInstanceConflictReason = "worker_instance_conflict: another Human worker is already connected with this token"
	// WorkerOwnershipViolationReason identifies a connection principal trying
	// to publish into a completion owned by another authenticated worker. This
	// is a connection-level authorization failure, not a rejectable business
	// event, so clients must stop reconnecting with the same outbox and token.
	WorkerOwnershipViolationReason = "worker_ownership_violation: event targets a completion owned by another worker"
)

type MessageType string

const (
	MessageHello         MessageType = "hello"
	MessageAssignment    MessageType = "assignment"
	MessageEvent         MessageType = "event"
	MessageEventRejected MessageType = "event_rejected"
	MessageAck           MessageType = "ack"
)

type Envelope struct {
	Version string          `json:"version"`
	Seq     uint64          `json:"seq"`
	Ack     uint64          `json:"ack"`
	Type    MessageType     `json:"type"`
	Payload json.RawMessage `json:"payload,omitempty"`
}

func NewEnvelope(messageType MessageType, payload any) (Envelope, error) {
	var raw json.RawMessage
	if payload != nil {
		encoded, err := json.Marshal(payload)
		if err != nil {
			return Envelope{}, err
		}
		raw = encoded
	}
	return Envelope{Version: Version, Type: messageType, Payload: raw}, nil
}

func (envelope Envelope) Validate() error {
	if envelope.Version != Version {
		return fmt.Errorf("unsupported worker protocol version %q", envelope.Version)
	}
	switch envelope.Type {
	case MessageHello, MessageAssignment, MessageEvent, MessageEventRejected, MessageAck:
	default:
		return fmt.Errorf("unsupported worker message type %q", envelope.Type)
	}
	if envelope.Seq == 0 {
		return errors.New("worker message seq must be positive")
	}
	return nil
}

type Hello struct {
	WorkerID string `json:"worker_id"`
}

type Event struct {
	CallerID       string           `json:"caller_id"`
	IdempotencyKey string           `json:"idempotency_key"`
	Event          completion.Event `json:"event"`
}

// EventRejected is a non-fatal business response which resolves one durable
// worker outbox record without accepting it into a completion.
type EventRejected struct {
	CallerID       string `json:"caller_id"`
	IdempotencyKey string `json:"idempotency_key"`
	EventID        string `json:"event_id"`
	Message        string `json:"message"`
}
